name: Issue with Game
description: Report a bug or problem with the game or launcher.
title: "[Issue] "
body:
  - type: checkboxes
    attributes:
      label: Before You Submit
      description: Please confirm the following.
      options:
        - label: I have checked for existing and open issues to avoid duplicates.
          required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Installation Method
      description: How did you install Strinova?
      multiple: false
      options:
        - From Lutris
        - From Bottles
        - YAML Script
        - Manually
      default: 0
    validations:
      required: true

  - type: input
    id: wine-version
    attributes:
      label: Wine Version (if applicable)
      description: Only required if installed manually or if you changed the Wine version.
      placeholder: e.g. lutris-GE-Proton8-10 or wine-9.0
    validations:
      required: false

  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: e.g. NVIDIA RTX 3070 or AMD RX 6700XT
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System Info
      description: Your Linux distribution, desktop environment, and display server.
      placeholder: e.g. Fedora 42, KDE 6, Wayland
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What Happened?
      description: Describe the issue in detail. What did you expect to happen, and what actually happened?
      placeholder: The game crashes after launch... or Launcher does not show any games...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (Optional)
      description: If possible, list steps to reproduce the issue.
      placeholder: |
        1. Open Lutris
        2. Launch Strinova
        3. Click "Start Game"
        4. Game freezes on loading screen
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs or Terminal Output
      description: Include any relevant logs from Lutris, Bottles, terminal, or crash dumps.
      render: shell
      placeholder: |
        Paste relevant log output here.
        You can also attach log files if needed.
    validations:
      required: false

  - type: dropdown
    id: occurrence
    attributes:
      label: Where Did the Issue Occur?
      multiple: false
      options:
        - Game
        - Launcher
      default: 0
    validations:
      required: true
